In [1]:
import numpy as np
import pandas as pd
import random

In [2]:
dataset1 = np.zeros([100, 20001], dtype = object)
dataset2 = np.zeros([100, 50001], dtype = object)
dataset3 = np.zeros([1000, 20001], dtype = object)
dataset4 = np.zeros([1000, 50001], dtype = object)

In [3]:
totalCasos1 = int(0.5*dataset1.shape[0])
totalCasos2 = int(0.5*dataset2.shape[0])
totalCasos3 = int(0.5*dataset3.shape[0])
totalCasos4 = int(0.5*dataset4.shape[0])
print(totalCasos1, totalCasos2, totalCasos3, totalCasos4)

50 50 500 500


In [4]:
for i in range(0, dataset1.shape[0]):
    dataset1[i,0:dataset1.shape[1]-1] = np.random.randint(3, size=dataset1.shape[1]-1)
    if(np.count_nonzero(dataset1[:,dataset1.shape[1]-1] == 'Caso')<totalCasos1):
        dataset1[i,dataset1.shape[1]-1] = random.choice(['Caso', 'Controle'])
    else:
        dataset1[i,dataset1.shape[1]-1] = 'Controle'
dataset1

array([[0, 2, 2, ..., 1, 1, 'Caso'],
       [2, 2, 0, ..., 1, 0, 'Controle'],
       [1, 0, 2, ..., 1, 0, 'Controle'],
       ...,
       [2, 0, 2, ..., 1, 1, 'Controle'],
       [0, 1, 1, ..., 1, 1, 'Caso'],
       [0, 2, 1, ..., 1, 2, 'Controle']], dtype=object)

In [5]:
for i in range(0, dataset2.shape[0]):
    dataset2[i,0:dataset2.shape[1]-1] = np.random.randint(3, size=dataset2.shape[1]-1)
    if(np.count_nonzero(dataset2[:,dataset2.shape[1]-1] == 'Caso')<totalCasos2):
        dataset2[i,dataset2.shape[1]-1] = random.choice(['Caso', 'Controle'])
    else:
        dataset2[i,dataset2.shape[1]-1] = 'Controle'
dataset2

array([[0, 2, 2, ..., 1, 1, 'Controle'],
       [1, 2, 2, ..., 0, 2, 'Controle'],
       [2, 1, 2, ..., 0, 0, 'Controle'],
       ...,
       [0, 0, 1, ..., 1, 1, 'Caso'],
       [0, 1, 1, ..., 0, 1, 'Controle'],
       [1, 2, 1, ..., 1, 1, 'Controle']], dtype=object)

In [6]:
for i in range(0, dataset3.shape[0]):
    dataset3[i,0:dataset3.shape[1]-1] = np.random.randint(3, size=dataset3.shape[1]-1)
    if(np.count_nonzero(dataset3[:,dataset1.shape[1]-1] == 'Caso')<totalCasos3):
        dataset3[i,dataset3.shape[1]-1] = random.choice(['Caso', 'Controle'])
    else:
        dataset3[i,dataset3.shape[1]-1] = 'Controle'
dataset3

array([[2, 0, 2, ..., 0, 1, 'Caso'],
       [1, 0, 0, ..., 2, 1, 'Controle'],
       [1, 0, 0, ..., 1, 1, 'Caso'],
       ...,
       [2, 1, 1, ..., 0, 0, 'Controle'],
       [1, 1, 1, ..., 0, 1, 'Controle'],
       [2, 1, 0, ..., 1, 1, 'Controle']], dtype=object)

In [7]:
for i in range(0, dataset4.shape[0]):
    dataset4[i,0:dataset4.shape[1]-1] = np.random.randint(3, size=dataset4.shape[1]-1)
    if(np.count_nonzero(dataset4[:,dataset4.shape[1]-1] == 'Caso')<totalCasos4):
        dataset4[i,dataset4.shape[1]-1] = random.choice(['Caso', 'Controle'])
    else:
        dataset4[i,dataset4.shape[1]-1] = 'Controle'
dataset4

array([[1, 2, 0, ..., 1, 2, 'Controle'],
       [1, 2, 2, ..., 1, 2, 'Controle'],
       [0, 1, 2, ..., 2, 0, 'Controle'],
       ...,
       [0, 0, 0, ..., 1, 2, 'Controle'],
       [0, 0, 0, ..., 1, 1, 'Controle'],
       [2, 0, 1, ..., 1, 2, 'Controle']], dtype=object)

In [8]:
df1 = pd.DataFrame(dataset1)
df1.to_csv("dataset1.csv", index = False)
df1.head()

0     1     2     3     4     5     6     7     8     9      ... 19991  \
0     0     2     2     0     2     1     1     2     0     1  ...     2   
1     2     2     0     2     1     0     1     1     1     1  ...     1   
2     1     0     2     0     0     0     1     2     0     0  ...     1   
3     2     2     2     0     0     0     0     1     2     2  ...     1   
4     1     2     0     2     1     0     1     0     0     1  ...     0   

  19992 19993 19994 19995 19996 19997 19998 19999     20000  
0     0     1     2     0     0     1     1     1      Caso  
1     1     2     0     2     2     2     1     0  Controle  
2     1     0     0     0     2     1     1     0  Controle  
3     2     1     1     1     2     1     2     0      Caso  
4     2     2     0     0     0     1     1     1      Caso  

[5 rows x 20001 columns]

In [9]:
df2 = pd.DataFrame(dataset2)
df2.to_csv("dataset2.csv", index = False)
df2.head()

0     1     2     3     4     5     6     7     8     9      ... 49991  \
0     0     2     2     2     0     2     1     1     1     1  ...     1   
1     1     2     2     0     1     0     1     1     2     2  ...     2   
2     2     1     2     0     1     2     0     2     2     0  ...     1   
3     0     1     2     0     2     1     0     0     0     2  ...     2   
4     1     1     1     2     0     0     1     0     1     2  ...     2   

  49992 49993 49994 49995 49996 49997 49998 49999     50000  
0     2     0     0     0     1     0     1     1  Controle  
1     0     2     2     2     2     0     0     2  Controle  
2     0     2     0     1     0     0     0     0  Controle  
3     2     1     1     2     1     1     2     2  Controle  
4     1     1     2     1     0     0     1     2  Controle  

[5 rows x 50001 columns]

In [10]:
df3 = pd.DataFrame(dataset3)
df3.to_csv("dataset3.csv", index = False)
df3.head()

0     1     2     3     4     5     6     7     8     9      ... 19991  \
0     2     0     2     0     2     1     2     0     0     0  ...     0   
1     1     0     0     1     1     0     0     2     2     1  ...     0   
2     1     0     0     1     0     2     2     0     2     1  ...     0   
3     2     0     1     1     1     1     1     0     0     1  ...     2   
4     2     2     2     1     1     2     1     1     2     2  ...     1   

  19992 19993 19994 19995 19996 19997 19998 19999     20000  
0     2     0     0     1     1     1     0     1      Caso  
1     0     1     0     1     2     2     2     1  Controle  
2     0     0     0     2     0     2     1     1      Caso  
3     0     0     2     0     0     1     0     2  Controle  
4     0     2     0     2     2     1     2     2      Caso  

[5 rows x 20001 columns]

In [11]:
df4 = pd.DataFrame(dataset4)
df4.to_csv("dataset4.csv", index = False)
df4.head()

0     1     2     3     4     5     6     7     8     9      ... 49991  \
0     1     2     0     2     2     2     1     0     0     1  ...     1   
1     1     2     2     1     1     2     0     1     1     2  ...     0   
2     0     1     2     0     0     1     0     1     2     0  ...     1   
3     2     0     2     0     0     2     1     1     1     0  ...     1   
4     2     2     0     2     0     1     2     2     2     1  ...     2   

  49992 49993 49994 49995 49996 49997 49998 49999     50000  
0     2     1     2     1     2     1     1     2  Controle  
1     1     2     0     2     2     2     1     2  Controle  
2     2     1     2     2     0     2     2     0  Controle  
3     2     2     2     0     1     0     1     2  Controle  
4     2     0     2     2     1     1     0     1  Controle  

[5 rows x 50001 columns]